# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bcb1f177ad2df597d1d944706c42bd7c02b00503c43f0e1a50cd761954efd7a23ef72eb58f22ca9df33aa202a77da1deeb73a451bb21ab52c76bf51e5527d0c

test:
  secret_key_base: f700d3aeae46789f90abe45fcc5eaf4757dfe1da14375f91078d371b619731ce8b88559f95882665433b236966ee7edc29b2ab6082a8c3de472398fb35a97b7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 24d0ba6959e7ec3cc3b40700181bb9b1eb081b47df4a420f8b6a71056f2805e61f323820c26d5dd5223467997a02e3b827957c29f18446ec7c5756706bdaf07d
